---
on:
  push:

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build tools
        run: sudo apt install cmake ninja-build
      - name: Build project
        run: |
          cmake --preset ninja-release-with-tests
          cmake --build build/release-with-tests
      - name: Run tests
        run: |
          cd build/release-with-tests
          ctest
